[Database]
# Must be one of [sqlite, mysql, postgresql]
# In case of sqlite only Driver and Name are required. 
Driver = ""
# Name specifies the name of the database or the path of the file in case of sqlite.
# 
# sqlite specific:
#   You can specify either an absolute or relative path.
#   If a relative path is used, the WorkingDirectory setting from the service file applies.
Name = ""
# The following setting only apply if Driver is one of [mysql, postgresql]
Host = ""
Port = 0
User = ""
Password = ""

[Mail]
Host = ""
# Based on the port, TLS support will be enabled or disabled
Port = 587
# The From string of the mail in the format RFC5322.
# E.g.: Rustymon <rustymon@example.com>
# or: rustymon@example.com
From = ""
# The user to perform the login at the mail server.
User = ""
Password = ""

[Server]
ListenAddress = "127.0.0.1"
ListenPort = 8080
# This defines the address, rustymon is available for users.
# E.g.: https://rustymon.example.com or http://rustymon.example.com:8080
PublicURI = ""
TemplateDir = "templates/"

[Logging]
LogFile = "/var/log/rustymon-server/rustymon.log"
# This specifies the size in MB a log file can have until a rotation is executed.
LogMaxCapacity = 20
# Specifies the number of days until, regarding of size, a rotation is executed.
LogMaxDays = 7
# Specifies the number of backups to retain
LogMaxBackups = 4
# Sets the queue size for the logger. If set to 0, a logging call will be blocking
LogQueueSize = 100

[Rustymon]
# Registration via app can be disabled by changing this field to true.
# This will remove the API endpoint "/register". Registration via CLI is still possible.
RegistrationDisabled = false
# As configurting a mailserver is required to allow self-service password reset, it is possible to disable this
# functionality with this setting
PasswordResetDisabled = false